site_name: Learning Python
repo_url: https://pranabdas.github.io/
site_description: My notes on learning python.
site_author: Pranab Das

nav:
    - Table of Contents: index.md
    - The Basics:
          - Introduction: introduction/introduction.md
          - Setting up: introduction/setup.md
          - Get started: introduction/basics.md
          - More on string formatting: introduction/string-formatting.md
          - Python Lists and Tuple: introduction/list-and-tuple.md
          - Dictionary: introduction/dictionary.md
          - "if-else condition": introduction/if-else.md
          - "while loop, break, continue": introduction/while-loop.md
          - Simple function: introduction/function.md
          - "File read-write": introduction/file-read-write.md
          - Python class: introduction/class.md
          - Python packages: introduction/python-packages.md
          - Virtual environment: introduction/venv.md
    - Numerical Python:
          - numpy: numerical-python/numpy.md 
          - Matrix algebra: numerical-python/matrix-algebra.md
    - Matplotlib:
          - Basic Matplotlib: matplotlib/matplotlib.md
          - Subplots: matplotlib/subplot.md 
          - Histogram: matplotlib/histogram.md 
          - Contour plot: matplotlib/contour-plot.md 
          - Image plot: matplotlib/image-plot.md
          - Create custom color map: matplotlib/custom-color-map.md
          - Function plot: matplotlib/function-plot.md 
          - Advanced 3D plots: matplotlib/3d-plots.md 
          - Customizing Matplotlib: matplotlib/custom-matplotlib.md 
    - scipy:
          - Integration using scipy: scipy/integration.md
          - Convolution: scipy/convolution.md 
          - Curve fitting: scipy/curve-fit.md 
    - Pandas:
          - Pandas Series and Dataframe: pandas/pandas.md
          - CSV and excel: pandas/csv-excel.md
    - Data Science: 
          - Packages: data-science/packages.md 
          - Data Exploration: data-science/data-exploration.md
          - Linear regression: data-science/linear-regression.md
    - Machine Learning: 
          - ML Introduction: machine-learning/ml.md 
          - Basic Probability and statistics: machine-learning/probability-statistics.md
          - Nearest neighbor classification: machine-learning/nearest-neighbor.md 
          - K-nearest neighbor: machine-learning/knn.md 
          - Generative model: machine-learning/generative-model.md 
          - Regression: machine-learning/regression.md 
    - Geopands:
          - Geo-maps: geopandas/maps.md
    - Django:
          - Django: django/django.md
          - Today app: django/today.md
          - To Do List App: django/todo.md
          - Airline app: django/airline.md
          - Django learning log: django/learning-log.md
    - Databases: 
          - SQL basics: database/sql.md
    - Misc:
          - Miscellaneous: misc/misc.md
          - Read data from url: misc/read-data-url.md
    - Projects:
          - Singapore traffic camera: projects/singapore-traffic-camera.md
          - AES-256 encryption: projects/directory-encryption.md 
          - Encrypt and upload to Dropbox: projects/encrypt-upload-dropbox.md

theme:
    name: null
    custom_dir: simplicity
    static_templates:
        - 404.html

    include_search_page: true
    search_index_only: false

    highlightjs: true
    hljs_languages: [python]

markdown_extensions:
    - pymdownx.arithmatex
    - attr_list

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML

dev_addr: '127.0.0.1:8001'
